### ISSUE TITLE
数据集的目录不一致

### ISSUE THREAD

**Issue by zjuzhq** [FangYang970206/Anime_GAN#1]
你好，在DCGAN中，main.py中的数据集目录是faces，AnimeDataset的数据集目录是anime，两者不一致。
main.py:
line24--parse.add_argument("--dataset", type=str, default="faces",
line47--if os.path.exists("faces"):
AnimeDataset
line25--dataset = AnimeDataset(os.getcwd(),"anime",100)
同时，在你的博客[https://www.cnblogs.com/fydeblog/p/9439024.html#1508482226](https://www.cnblogs.com/fydeblog/p/9439024.html#1508482226)中，DCGAN的main.py中的if os.path.exists("faces"): 应该修改为 if os.path.exists("anime"):，或者把另外2个目录名称修改一下

**Comment by FangYang970206** [comment]
好的，压缩文件是faces，我把anime改成faces，保持一致就好，谢谢！
