### ISSUE TITLE
How to apply conditional GAN to my custom dataset

### ISSUE THREAD

**Issue by ghost** [FangYang970206/Anime_GAN#3]
I created my own dataset which have only 4 types of hair color tags (Blue, Pink, Yellow and Green). Is it possible to try with your code? Is there something I have to change? 
Thank you

**Comment by FangYang970206** [comment]
You need to modify the load_Anime and test_Anime functions in utils.py files, especially the tag_dict variable. Note the image size, I use 64x64. If the image sizes are different, you need to slightly modify the network to adapt your image size. The rest can remain unchanged.

**Comment by ghost** [comment]
Thank you so much!

**Comment by ghost** [comment]
I have trying to put my own data but it shows some error...
Do I need to change the structure? cause I have only 4 tags..I am not sure if it related.
sorry for  many questions. I am very new in GAN

<img width="1201" alt="Screen Shot 2563-03-10 at 21 46 08" src="https://user-images.githubusercontent.com/51433046/76324660-ee80ba00-6318-11ea-9e1a-770ccaa384fb.png">


my image size  64x64

**Comment by FangYang970206** [comment]
You need to change 407(384+23) to 388 (384+4) in [this line](https://github.com/FangYang970206/Anime_GAN/blob/42c0315c24bc59fb3bb8e417882b6c064fcf0cc2/ConditionalGAN/CGAN.py#L57)

**Comment by FangYang970206** [comment]
my tags are 23, your tags are 4. Tags feature is added to the discriminator to discriminate different tags.

**Comment by FangYang970206** [comment]
Also, you need to change 23 to 4 in [this line](https://github.com/FangYang970206/Anime_GAN/blob/42c0315c24bc59fb3bb8e417882b6c064fcf0cc2/ConditionalGAN/CGAN.py#L95).

**Comment by ghost** [comment]
Oh now It's working! Thank you so much for your helping

**Comment by ghost** [comment]
Hello, I am facing another problems...
it seems to be work but...
I got an error after training for 10 epochs… when the step is 1000

> Traceback (most recent call last):
>   File "main.py", line 45, in <module>
>     main()
>   File "main.py", line 39, in main
>     gan.train()
>   File "/content/CGAN.py", line 147, in train
>     image = generate(torch.from_numpy(z).float().to(self.device),torch.from_numpy(y).float().to(self.device)).to("cpu").detach().numpy()
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/content/CGAN.py", line 38, in forward
>     z = torch.cat((z,y), dim=-1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 120 and 25 in dimension 0 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

Maybe it happened because of my dataset... not sure
but I already checked size(64*64) and all of them are RGB.

Thinking....maybe its about this line in utils.py?

`z = np.random.normal(0, np.exp(-1 / np.pi), [25, 62])
`

Thanks!

**Comment by ghost** [comment]
I also changed this line in CGAN.py
from 5000 to 1000 
```
#show result and save model 
                if (step)%1000 == 0:
```
That’s the reason of error?

**Comment by FangYang970206** [comment]
You need to modify the test_anime function. The generator has two inputs, one is the normally distributed variable z, and the other is the label attribute y, z and y need to be equal in dimension 0, for example, `z = np.random.normal(0, np.exp(-1 / np.pi), [25, 62]) -> z.shape is (25, 62)`, and y should be (25, x),  in my anime , x is 23. 25 represents the total number of pictures to be generated, such as the sample picture of conditional gan in readme. I don't know if your test.txt has been modified, mine is 5 categories, each category generates 5 examples. So it's 25. The error message shows that 120 and 25 cannot be concatenated in dimension 0, which means you want to concatenate (120, 62) and (25, 4) two arrays, which is impossible. Print array size debugging.

**Comment by FangYang970206** [comment]
At the beginning, (step)%1000 can be changed to (step)%5, and it will take less time to see if it works.

**Comment by ghost** [comment]
I have modified it, Finally It's really work~
I appreciate for your help and time
Thank you so much
